
commands_factory.o: commands_factory.cpp commands_factory.h
	g++ -g -std=c++17 -c command.o -o commands_factory.o commands_factory.cpp

command.o: command.cpp command.h
	g++ -g -std=c++17 -c -o command.o command.cpp
